### ISSUE TITLE
vue 3 

### ISSUE THREAD

**Issue by feddelegrand7** [timelyportfolio/vueR#10]
Hi, sorry to bother @timelyportfolio but any attempt to configure vueR in order to make it working with the new vue 3 release ? 

Best. 
Fodil.

**Comment by timelyportfolio** [comment]
Thanks for the question and very sorry for the delayed response.  My current thought is to create a second set of parallel functions with a *3 pattern.  I hope to get something prior to year-end and certainly before official release of `vue` 3.

I'd love your thoughts.

**Comment by feddelegrand7** [comment]
Hi, thanks for your reply. Yeah it would be great.  Thank you so much for your efforts. I'm still learning vue3 but if I can help with something, don't hesitat :)

**Comment by timelyportfolio** [comment]
@feddelegrand7 I plan to add vue 3 this month -- a year later 😞

**Comment by feddelegrand7** [comment]
Hi @timelyportfolio haha I totally understand. It's quite challenging to find some time for open source projects these days ^^. Thanks again for your excellent R contribution.

**Comment by timelyportfolio** [comment]
@feddelegrand7 I did not meet my December 2021 goal, but for a good start to the year I just added `vue@3` experimental support in the `dev` branch.  If you have some time, I would very much appreciate trying it out with `remotes::install_github("vue-r/vueR@dev)`.  In general I added `3` to the R functions to denote `vue@3` - for instance instead of `vue()` use `vue3()`.

https://github.com/vue-r/vueR/blob/dev/inst/examples/vue3_widget_examples.R
https://github.com/vue-r/vueR/blob/dev/inst/examples/vue3_shiny_examples.R

**Comment by feddelegrand7** [comment]
Hi @timelyportfolio happy new year and thanks again for the feature, I'm very excited about although I haven't touched vue for a while! I'll test ASAP. 

Best,
Fodil.

**Comment by timelyportfolio** [comment]
submitted and accepted to CRAN with vue3 functions
